### ISSUE TITLE
Adding a new project: Fetal Health Classification

### ISSUE THREAD

**Issue by nandinib1999** [kritikaparmar-programmer/HealthCheck#10]
I would like to add a new project under the HealthCheck - Fetal Health Classification. I came across the dataset on Kaggle and it looked really interesting.
https://www.kaggle.com/andrewmvd/fetal-health-classification

I am a GSSOC'21 participant

**Comment by kritikaparmar-programmer** [comment]
Hey, @nandinib1999 I found the idea really interesting, I'm assigning this issue to you. Do remember to make a pr when the contribution period for GSSOC'21 starts. Happy Coding :)

**Comment by nandinib1999** [comment]
Hi, thanks a lot!

I am participating in GSSOC'21 for the first time, so what to confirm - are there any deadlines for the PR submission after the contribution period starts?

**Comment by kritikaparmar-programmer** [comment]
You'll be provided with 7 days to work on an issue, If you'll not submit a pr for the same in that period, the next one who comments to work on that issue will be assigned. So don't worry you'll have one week to work on one issue :)

**Comment by nandinib1999** [comment]
Okay, thanks a lot for clearing up that!
