### ISSUE TITLE
Improving the efficiency/performance of the Breast cancer model

### ISSUE THREAD

**Issue by Divyang0601** [kritikaparmar-programmer/HealthCheck#104]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by manan-bedi2908** [comment]
@Divyang0601 Assigned to you!! Go ahead

**Comment by shubhigupta991** [comment]
Any Updates?

**Comment by Divyang0601** [comment]
Almost done

**Comment by shubhigupta991** [comment]
fixed in #120
