### ISSUE TITLE
Adding IoT feature to obtain realtime health parameters

### ISSUE THREAD

**Issue by amandewatnitrr** [kritikaparmar-programmer/HealthCheck#105]
## Proposal

Adding IoT feature to obtain realtime health parameters. As far as we are helping, people identify these diseases, we can include some hardware, IoT based stuff that will help it to send realtime temperature, dissolved oxygen (SpO2), ssugar level etc. That can actually be a good idea.

Hardware requirements (I have them.):
1. Raspberry Pi/Arduino
2. Sensors (DSB1820 Temp Sensor, IR Temp Sensor, Pressure Sensor)

Software Requirements:
1. Firebase
2. Python/Arduino
3. Support from other developers for handling the API stuff.

**Comment by utkarsh0702** [comment]
@amandewatnitrr Your idea is great 👍.  But unfortunately we can't have it as in the end we would be releasing the website and the users will be using it, but they won't have the access to the IOT hardwares.
Even if we add it people couldn't acess it, so then what will we gain from adding it.
