### ISSUE TITLE
COVID19 Prediction

### ISSUE THREAD

**Issue by srimontidutta** [kritikaparmar-programmer/HealthCheck#106]
COVID19 Prediction through chest X-rays.

**Comment by utkarsh0702** [comment]
@srimontidutta I am assigning this issue to you

**Comment by srimontidutta** [comment]
Thanks!

**Comment by srimontidutta** [comment]
I'm still working on it, got stuck in a particular part. I'll make the PR by Monday.

**Comment by srimontidutta** [comment]
The code is completed. Do I have to include a readme file as well?

**Comment by kritikaparmar-programmer** [comment]
@srimontidutta It's up to you just made a pr of the changes the mentors will review.

**Comment by srimontidutta** [comment]
Thanks for the reply. I could not come online due to exams, I'll make the PR this weekend.
