### ISSUE TITLE
Addition of Thyroid Prediction

### ISSUE THREAD

**Issue by AryaPatel1111** [kritikaparmar-programmer/HealthCheck#107]
## **I had like to add thyroid prediction notebook and dataset to this project.**

- I will be taking the dataset of thyroid from University of California Irvine datasets https://archive.ics.uci.edu/ml/machine-learning-databases/thyroid-disease/sick-euthyroid.data

## **Adding the prediction of thyroid based on following features:**

- Age, Sex, Anti-thyroid medication, surgery for thyroid, on thyroxine, hypothyroid, sick, tumor, pregnant, TSH, T3, TT4, T4U, FTI.

**Comment by utkarsh0702** [comment]
@AryaPatel1111 We have already assigned thyroid prediction to someone else.
https://github.com/kritikaparmar-programmer/HealthCheck/issues/47
