### ISSUE TITLE
Pneumonia Detection Model

### ISSUE THREAD

**Issue by Anas-Issa** [kritikaparmar-programmer/HealthCheck#109]
I am a gssoc'21 participant, and I would like to add a Pneumonia detection model to the project.

I will be using the Chest X-Ray Images (Pneumonia) dataset:
[Dataset](https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia)

**Comment by utkarsh0702** [comment]
@Anas-Issa We already have it. https://github.com/kritikaparmar-programmer/HealthCheck/pull/30

**Comment by Anas-Issa** [comment]
@utkarsh0702 Sorry for the inconvenience, I will try to find another feature to be added to the project.
