### ISSUE TITLE
Fatty Liver Prediction

### ISSUE THREAD

**Issue by AryaPatel1111** [kritikaparmar-programmer/HealthCheck#111]
## **Addition of Fatty Liver disease**

- Predicting whether a person is going from fatty liver problem or not based on the level of different vitals and another different compound.

**Comment by AryaPatel1111** [comment]
@utkarsh0702 Can you please look into this and assign the issue to me.

**Comment by utkarsh0702** [comment]
@AryaPatel1111 Please share the link to the dataset

**Comment by kritikaparmar-programmer** [comment]
@AryaPatel1111 I think we are done with the diseases now we have to work on the connecting backend and frontend. So closing this issue for now as it's inappropriate.
