### ISSUE TITLE
Covid-19 Detection Model 

### ISSUE THREAD

**Issue by Anas-Issa** [kritikaparmar-programmer/HealthCheck#112]
I am a gssoc'21 participant.I would like to add a Covid-19 detection model to the project.

COVID-19 Chest X-ray Image Dataset: [Here](https://www.kaggle.com/alifrahman/covid19-chest-xray-image-dataset)

**Comment by utkarsh0702** [comment]
@Anas-Issa A previous issue has already been created.
Please close the issue.
For open issues look for the label Up for Grab.

**Comment by Anas-Issa** [comment]
OK
