### ISSUE TITLE
Time series forecasting covid 19 case

### ISSUE THREAD

**Issue by ayush-raj8** [kritikaparmar-programmer/HealthCheck#115]
We can use covid 19 data of last one year of India to forecast cases in near future. Dataset can be got for Ministry of health. I would like to work on it.

**Comment by ayush-raj8** [comment]
@manan-bedi2908 Please assign this to me, I'll come up with a jupyter notebook implementation at first.

**Comment by manan-bedi2908** [comment]
@ayush-raj8 Assigned to you! Go ahead
