### ISSUE TITLE
Improving efficiency for "Prediction of  presence of heart disease in the patient" Model Using Deep Learning

### ISSUE THREAD

**Issue by vaishnavipatil29** [kritikaparmar-programmer/HealthCheck#116]
I am GSSOC'21 Participant. I want to Improving efficiency for "Prediction of  presence of heart disease in the patient" Model Using Deep Learning. Please assign me the issue.

**Comment by utkarsh0702** [comment]
@vaishnavipatil29  All the mentors and the project admin decided not to give any model improvement issues to any one, as it will affect the points of the precious candidate and it is also an endless process.
Sorry for the unconvince, it took a while to decide.
You can create any new issue regarding flask or api or if you require an issue regarding ML then check for the label Up for Grab
