### ISSUE TITLE
unnecessary if block in certain routes 

### ISSUE THREAD

**Issue by priyanshu20** [kritikaparmar-programmer/HealthCheck#118]
There are certain routes which have only 1 acceptable HTTP verb ,
we do not need an if block in those routes as the code will be executed only if the request.method is the appropriate one.

Eg-

![redudancy](https://user-images.githubusercontent.com/59313375/112428996-11361300-8d62-11eb-92ce-5cc4f434a719.PNG)

Fix - 
remove the if block

**Comment by priyanshu20** [comment]
@utkarsh0702 what do u think about this?

**Comment by utkarsh0702** [comment]
@priyanshu20 We can leave it, as it's not creating any kind of bug and its just a single line of code.

**Comment by priyanshu20** [comment]
👍🏽 okay
