### ISSUE TITLE
Gssoc'21 Internal Server Error and Navbar toggle is not working

### ISSUE THREAD

**Issue by arpit456jain** [kritikaparmar-programmer/HealthCheck#119]
## **Describe the bug**

When I clicked on Predict without entering any data it leads to  internal server error.
I occurs in three pages (Diabetes Prediction, Heart Disease Prediction, Cancer Prediction).
<img width="960" alt="health" src="https://user-images.githubusercontent.com/55352601/112480902-7d356d00-8d9c-11eb-85cd-678f0281c597.png">

Navbar toggle is not working.
There should be a redirect link to home page in "HEALTH CHECK"  which is in left side in navbar.

And There is some responsiveness problem in some places.
Content in Footer is not in Center
I am attaching a video for better understanding of my issues.

https://user-images.githubusercontent.com/55352601/112481955-8d9a1780-8d9d-11eb-845f-6a4f025b297a.mp4

## **Possible solution**
I have to work on it.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@shreyasZ10 @utkarsh0702 Can you please assign this to me .
I am a Gssoc'21 participant

**Comment by shubhigupta991** [comment]
Assigned @arpit456jain go ahead.

**Comment by arpit456jain** [comment]
@shubhigupta991 I had solved this issue May I create a PR.?

**Comment by arpit456jain** [comment]
@shubhigupta991 please review my PR.
