### ISSUE TITLE
Add a new project: Kidney disease prediction 

### ISSUE THREAD

**Issue by sudipg4112001** [kritikaparmar-programmer/HealthCheck#12]
I would like to add a new project for predicting kidney diseases. 
Using the dataset : https://www.kaggle.com/mansoordaku/ckdisease  
I am a participant of GSSOC'21

**Comment by kritikaparmar-programmer** [comment]
Hey @sudipg4112001, great idea, start working on it. 
Happy Coding :)

**Comment by sudipg4112001** [comment]
I have done a PR please review it.
