### ISSUE TITLE
Add new Project : Cardiovascular Disease Prediction

### ISSUE THREAD

**Issue by NEERAJAP2001** [kritikaparmar-programmer/HealthCheck#124]
## **Is your feature request related to a problem? Please describe.**
I would Like to add "Cardiovascular disease Prediction" to this project.
Dataset - [Here](https://www.kaggle.com/aiaiaidavid/cardio-data-dv13032020)

## **Describe the solution you'd like**
Follow the ML Pipeline from cleaning to prediction And saving the best model into a pkl File.

I'd Like to work on this as part of GSSOC-21.

**Comment by utkarsh0702** [comment]
@NEERAJAP2001 No more diseases please.
If you want to work on flask or api you can create an issue.
Please close the pr.

**Comment by NEERAJAP2001** [comment]
okay @utkarsh0702
