### ISSUE TITLE
<GSSoC'21>Pulse rate measurement through Webcam

### ISSUE THREAD

**Issue by sayan9112** [kritikaparmar-programmer/HealthCheck#127]
Hi Sayan here. I'm a GSSoC'21 participant.
I found your project insightful and want to contribute.
I would like to add a new feature **Pulse rate measurement through Webcam**.

Please assign me in this issue.

**Comment by utkarsh0702** [comment]
@sayan9112 Can you please explain it a bit more.

**Comment by sayan9112** [comment]
@utkarsh0702 
using open CV we can detect users forehead region.  Data is collected from this location over time to estimate the user's heart rate. This is done by measuring average optical intensity in the forehead location, in the subimage's green channel alone.
With good lighting and minimal noise due to motion, a stable heartbeat should be isolated in about 15 seconds.

**Comment by utkarsh0702** [comment]
@sayan9112 What will people do by getting their pulse rate? Please give us a reason why we should add it.

**Comment by sayan9112** [comment]
@utkarsh0702 pulse rate is an important feature in any health check app or gadget. Hope you can get it.

**Comment by utkarsh0702** [comment]
@sayan9112 Please continue working, but we will be needing a test proof that the pulse rate your model provides is around the real pulse rate.
If you don't mind we would like to add to your idea, rather then pulse rate you can show the amount of oxygen level in the users body by first getting pulse rate and then converting it to the amount of oxygen in body.

**Comment by sayan9112** [comment]
@utkarsh0702 I've got your point.  Surely I'll implement  the other features, but let me do the base first. Please assign me.

**Comment by shubhigupta991** [comment]
@sayan9112 what's the update?

**Comment by sayan9112** [comment]
I'll  submit it via 16

**Comment by shubhigupta991** [comment]
its 21?

**Comment by sayan9112** [comment]
@shubhigupta991 I'm sorry, but due to some issues I can't submit the code.
