### ISSUE TITLE
[Gssoc'21] Dark Mode with Toggle Button.

### ISSUE THREAD

**Issue by arpit456jain** [kritikaparmar-programmer/HealthCheck#131]
## **Is your feature request related to a problem? Please describe.**
No
## **Describe the solution you'd like**

I thought dark-mode will be a cool feature

**Comment by arpit456jain** [comment]
@utkarsh0702 @HimanchalChandra  please assign it to me as I am a GSSoC'21 participant

**Comment by utkarsh0702** [comment]
> ## **Is your feature request related to a problem? Please describe.**
> No
> 
> ## **Describe the solution you'd like**
> I thought dark-mode will be a cool feature

In which web app or mobile app

**Comment by arpit456jain** [comment]
@utkarsh0702 in web app

**Comment by utkarsh0702** [comment]
@arpit456jain Ok

**Comment by arpit456jain** [comment]
@utkarsh0702 please review my PR
