### ISSUE TITLE
Adding retinal diabetes

### ISSUE THREAD

**Issue by akshitadixit** [kritikaparmar-programmer/HealthCheck#14]
I wish to work on this issue

**Comment by kritikaparmar-programmer** [comment]
Please provide some more details on this issue :)

**Comment by akshitadixit** [comment]
Diabetes has a complication when the glucose in the blood vessels starts to gradually affect the retina of the eye. This is called Diabetic Retinopathy. The dataset below is what I came accross. 

[Dataset](https://www.kaggle.com/c/diabetic-retinopathy-detection)

**Comment by kritikaparmar-programmer** [comment]
Assigning this issue to you @akshitadixit Happy Coding :)

**Comment by Sibasish-Padhy** [comment]
I wish to work on this issue

**Comment by kritikaparmar-programmer** [comment]
@akshitadixit updates?

**Comment by akshitadixit** [comment]
> @akshitadixit updates?

Yes. I am onto the tuning part. The weekend might do it.

**Comment by akshitadixit** [comment]
@kritikaparmar-programmer for some reason this issue isn't being counted in my gssoc profile, will it be counted after it is closed?

**Comment by akshitadixit** [comment]
Also I am halfway stuck in my CNN approach since the accuracy is very poor. Meanwhile I came across this [link](https://www.sciencedirect.com/science/article/pii/S2352914820302069) and seems like I might have to change either my approach and begin fresh or completely work on a new dataset.

You can unassign the issue to me if someone else is waiting in line, cz i am a beginner and will take time. I do not wish to copy the code and do it purely out of motivation. I hope you understand.

**Comment by shubhigupta991** [comment]
@Sibasish-Padhy are you interested in doing this?

**Comment by nandinib1999** [comment]
@shubhigupta991 I would like to give this a try!

**Comment by shubhigupta991** [comment]
Okay! Go ahead @nandinib1999

**Comment by kritikaparmar-programmer** [comment]
@nandinib1999 updates?

**Comment by nandinib1999** [comment]
Can I send PR by the weekend? I was a bit caught up in my college tests in the past week
