### ISSUE TITLE
Auto Label Bot

### ISSUE THREAD

**Issue by aishux** [kritikaparmar-programmer/HealthCheck#142]
## **Is your feature request related to a problem? Please describe.**

Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21. As it takes time for the maintainer to add labels, I can add a script that can auto-label issues with the GSSOC21 label whenever contributors ask to work under that label.

## **Describe the solution you'd like**

I would like to add a script to automate the process.

**Comment by aishux** [comment]
Please give me a level tag too.

**Comment by kritikaparmar-programmer** [comment]
Hey we give level tag in PR's only :)
