### ISSUE TITLE
[Gssoc'21] Contact Us Section 

### ISSUE THREAD

**Issue by arpit456jain** [kritikaparmar-programmer/HealthCheck#143]
## **Is your feature request related to a problem? Please describe.**

A contact us page can be added with form by which any user can contact to us ..

## **Describe the solution you'd like**
I can add a contact us section

**Comment by kritikaparmar-programmer** [comment]
Hey, @arpit456jain I think the contact us feature is not needed for this project. I've something else on my mind. 
Like we can have a link to this repo on the main page with GitHub logo, and we can write like this website is in production, feel free to raise an issue and contribute.
Tell me if you would like to work on this, I'll raise an issue and will assign you to it.

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer  I think contact us section is  not for queries for contributors. above approach also can be done no problem.
My main motive for contact us section is for the queries of people which will use this website.
Whom would they ask if they had any trouble or doubt.
If there will be contact page they can message us which can be saved in database or can be emailed.
People can suggest and can give feedback about website and features **and not every person use  GitHub**

**Comment by arpit456jain** [comment]
> @kritikaparmar-programmer I think contact us section is not for queries for contributors. above approach also can be done no problem.
> My main motive for contact us section is for the queries of people which will use this website.
> Whom would they ask if they had any trouble or doubt.
> If there will be contact page they can message us which can be saved in database or can be emailed.
> People can suggest and can give feedback about website and features **and not every person use GitHub**

@kritikaparmar-programmer should I close this issue if there is no need.?
