### ISSUE TITLE
[Gssoc'21] Add a dropdown menu

### ISSUE THREAD

**Issue by arpit456jain** [kritikaparmar-programmer/HealthCheck#144]
## **Is your feature request related to a problem? Please describe.**

I want to add a drop-down menu in navbar which will  contain all  links of types of checks like this.
<img width="614" alt="nav" src="https://user-images.githubusercontent.com/55352601/113319255-e08c4580-932e-11eb-815b-27096338ed50.png">

Currently we have to go to home page for going for any check after this we can go to any page .

**Comment by kritikaparmar-programmer** [comment]
Nice idea @arpit456jain Go ahead 🚀

**Comment by arpit456jain** [comment]
thanks for assigning I will make a PR very soon.

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer kindly add the label of level as i didn't get any points for it.
