### ISSUE TITLE
Heart Disease Prediction Issues

### ISSUE THREAD

**Issue by aakriti1318** [kritikaparmar-programmer/HealthCheck#15]
1. Variables names vary which lead to the error (Dataset is mentioned as Data somewhere). 
2. 'rcParams' is not defined.
3. I would like to apply other algorithms to improve accuracy. (SVM, Random Forest, Xgboost)
4. Finally to check the accuracy of the model.

Please assign me to solve these issues. @kritikaparmar-programmer

**Comment by kritikaparmar-programmer** [comment]
Hey @aakriti1318 can you provide screenshots of the issues you are providing it will be easier for me to look. Then I can assign this to you.

**Comment by aakriti1318** [comment]
Hey @kritikaparmar-programmer, Yes surely 
Here is the snapshot for the 1st issue.
![image](https://user-images.githubusercontent.com/56245613/110214021-a911b100-7ec8-11eb-96ce-8d87817511f2.png)

For the second issue:  'rcParams' is not defined.
![image](https://user-images.githubusercontent.com/56245613/110214172-70260c00-7ec9-11eb-94f7-fa6518608437.png)


For the 4th issue, you can assign me to check the accuracy.

**Comment by kritikaparmar-programmer** [comment]
Yeah I looked at the notebook there are some issues, Go ahead @aakriti1318 assigning this issue to you :)
