### ISSUE TITLE
Flask Route for Liver Disease Prediction

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [kritikaparmar-programmer/HealthCheck#151]
Create a Flask Route for Liver Disease Prediction
Model - The liver-disease model is in the Models folder.

**Comment by JanhaviSoni** [comment]
@kritikaparmar-programmer Please assign this issue.

**Comment by ayush-raj8** [comment]
@kritikaparmar-programmer I can give it a try if assigned , worked with flask backend earlier.

**Comment by kritikaparmar-programmer** [comment]
@JanhaviSoni I'm assigning you on a first come first serve basis. Feel free to reach out to any mentor or me if you face any problems. Happy Coding :)

**Comment by JanhaviSoni** [comment]
@kritikaparmar-programmer I just have to add flask route and need not add .html files . If so what should I pass give the some name which can be made by someone.

**Comment by kritikaparmar-programmer** [comment]
Yes, @JanhaviSoni flask route means the complete path from frontend to the backend. Still if you're facing problem juts make a pr of what you're able to do, we will assign you the points accordingly :)

**Comment by JanhaviSoni** [comment]
@kritikaparmar-programmer  we need to push to dev branch
