### ISSUE TITLE
Disease Page for User Category

### ISSUE THREAD

**Issue by utkarsh0702** [kritikaparmar-programmer/HealthCheck#154]
Disease Page will contain all the diseases out of which user will choose one. The UI can be kind of similar to the Category page.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by utkarsh0702** [comment]
@AshuKV This issue is to develope in flutter

**Comment by Borahb** [comment]
Can you assign me this issue? #gssoc21

**Comment by utkarsh0702** [comment]
@Borahb Sure

**Comment by Borahb** [comment]
@utkarsh0702  how should the UI look like ?

**Comment by Borahb** [comment]
@utkarsh0702 have a look on this UI
![Screenshot_1617805681](https://user-images.githubusercontent.com/49881148/113883398-c0033600-97db-11eb-85d5-7c425ccb6190.png)

**Comment by utkarsh0702** [comment]
@Borahb we will keep the UI simple, and the screenshot you send will work fine. Just one thing, why is it blur. We will add images in place of colored containers

**Comment by Borahb** [comment]
@utkarsh0702  the blur is due to offset. Okay, then should I push this page with this UI.

**Comment by utkarsh0702** [comment]
@Borahb ok, just do one thing get the names of a few of the disease that the project have, get an image for every disease and put them in place of these colored boxes and place an empty onTap functionality.
Do the changes and create a pr.

**Comment by Borahb** [comment]
@utkarsh0702  Actually  I am not able to find the appropriate picture of the disease to be used here. Like it would be better if PA selects the right picture for it. So, can I push with the present UI?

**Comment by utkarsh0702** [comment]
Okay then just leave an alternative image there, i will replace them. Create a pr.
