### ISSUE TITLE
Page for Parkinson Disease Prediction

### ISSUE THREAD

**Issue by utkarsh0702** [kritikaparmar-programmer/HealthCheck#155]
Page will contain the form text field in which user will enter the values and click on submit button to get result. Validation for empty and type missmatch should be added.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by utkarsh0702** [comment]
@AshuKV This is for the mobile app, you know that right. If you are comfortable with flutter, I am happy to assign this issue to you.

**Comment by AshuKV** [comment]
Hey @utkarsh0702 I am not acknowledged with flutter, please assign it to somebody else.

**Comment by Borahb** [comment]
Can I Work on this issue under gssoc'21? I  am comfortable with flutter.

**Comment by utkarsh0702** [comment]
@Borahb Sure. Please see the existing UI and please push your changes on flutter branch. I am assigning it to you.

**Comment by Borahb** [comment]
okay

**Comment by Borahb** [comment]
@utkarsh0702  Have a look this UI
![Screenshot_1617805708](https://user-images.githubusercontent.com/49881148/113883549-df9a5e80-97db-11eb-86d5-9a10a665ac53.png)
![Screenshot_1617805715](https://user-images.githubusercontent.com/49881148/113883555-e0cb8b80-97db-11eb-8ca7-01019114e8e6.png)

**Comment by utkarsh0702** [comment]
@Borahb The UI looks good but please change the color of the button and also you need to add one validation of not leaving it empty and if there are fixed options like gender, where there are 2 options only, you can use radio button instead of text field.

**Comment by Borahb** [comment]
@utkarsh0702 okay suggest some colors and I have added validation for not leaving it empty.

**Comment by utkarsh0702** [comment]
@Borahb add any color that suits the dark theme, red is just kind of a pinching color that why i asked to change it.
