### ISSUE TITLE
Improving Diabetes model performance(Accuracy improved from 79 to 89 percent) with proper data analysis

### ISSUE THREAD

**Issue by Divyang0601** [kritikaparmar-programmer/HealthCheck#157]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by Divyang0601** [comment]
The current diabetes model that is present in the repository, predicts the presence of disease with 79 percent accuracy.

With proper feature engineering and analysis, I have come up with a model that predicts diabetes with more than 89 percent accuracy, along with excellent precision, recall and F1 score

**Comment by utkarsh0702** [comment]
@Divyang0601 Assigning it to you.
