### ISSUE TITLE
Update DiabetesNotebook.ipynb

### ISSUE THREAD

**Issue by aayushibansal2001** [kritikaparmar-programmer/HealthCheck#16]
The notebook is not complete with the training the model and predicting the output of the trained model. So I would like to solve this issue by adding both these things to this DiabetesNotebook.ipynb

I am a participant of GSSOC'21.

**Comment by kritikaparmar-programmer** [comment]
Go ahead @aayushibansal2001 , make sure to save the model and try to make more visuals if possible, Happy Coding :)

**Comment by spsrathor** [comment]
The model made in this notebook ( RandomForest ) is having only 80% accuracy. I will like to improve the accuracy of same by trying other models.

I am also in GSSOC21
