### ISSUE TITLE
Grammatical errors in the Readme file

### ISSUE THREAD

**Issue by anirudhsai20** [kritikaparmar-programmer/HealthCheck#162]
There are a lot of grammatical errors in the Readme file which needs correction.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by kritikaparmar-programmer** [comment]
Hey @anirudhsai20 please take a look at the pinned issues first #9 is always opened for such readme changes. I'm closing this issue, still you can work on this issue, just comment down in the #9 issue.
