### ISSUE TITLE
Improve tech stack in readme file with logos

### ISSUE THREAD

**Issue by srisatya1197** [kritikaparmar-programmer/HealthCheck#163]
I want to improve tech stack in readme file with logos. I'm a participant of GSSOC'21 please assign this issue to me.

**Comment by kritikaparmar-programmer** [comment]
Hey @srisatya1197 we have #9 issue always opened for the changes in Readme file, please don't open a new issue regarding any change in the readme. So you can work on the issue rn but in the future never do this.
