### ISSUE TITLE
Medical loan

### ISSUE THREAD

**Issue by sudipg4112001** [kritikaparmar-programmer/HealthCheck#17]
I would like to add a project, which predicts wheather medical loan will be approved to the patients family for treatment purpose. Using the dataset below.
https://www.kaggle.com/ninzaami/loan-predication?select=train_u6lujuX_CVtuZ9i+%281%29.csv

I am a GSSOC'21 participant

**Comment by kritikaparmar-programmer** [comment]
I think loan prediction is not needed, as this project is for disease predictions. @sudipg4112001  you can also give suggestions on this. Also, there are many diseases that are still left you can open issues for them.
