### ISSUE TITLE
[Gssoc'21] 404 page 

### ISSUE THREAD

**Issue by arpit456jain** [kritikaparmar-programmer/HealthCheck#172]
## **Is your feature request related to a problem? Please describe.**
There is not page for 404 request
<img width="960" alt="p11" src="https://user-images.githubusercontent.com/55352601/114022511-796f1380-988f-11eb-9641-76b159fdfb97.png">

## **Describe the solution you'd like**
I want to add a 404 page to it.

**Comment by kritikaparmar-programmer** [comment]
Nice idea @arpit456jain. Go ahead 🚀

**Comment by arpit456jain** [comment]
Ok @kritikaparmar-programmer  thanks

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/114156578-5c464d80-9940-11eb-83e5-17d4536bc834.mp4


https://user-images.githubusercontent.com/55352601/114156599-61a39800-9940-11eb-9460-1ff0c8c73f6a.mp4

@kritikaparmar-programmer how this .??
can I make a PR for this.

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer kindly select one of the above 404 page or tell me if I have to make another one .
then I can create a PR

**Comment by kritikaparmar-programmer** [comment]
>  2021-04-09.14-29-13.mp4 
>  2021-04-09.14-29-55.mp4 
> @kritikaparmar-programmer how this .??
> can I make a PR for this.

I think this one looks nice, great work @arpit456jain , you can make a pr for this :)

**Comment by arpit456jain** [comment]
> > 2021-04-09.14-29-13.mp4
> > 2021-04-09.14-29-55.mp4
> > @kritikaparmar-programmer how this .??
> > can I make a PR for this.
> 
> I think first one looks nice, great work @arpit456jain , you can make a pr for this :)

Ok @kritikaparmar-programmer i am making a PR

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer kindly review my PR
