### ISSUE TITLE
Adding flask route for malaria model and required frontend pages for the same

### ISSUE THREAD

**Issue by ayush-raj8** [kritikaparmar-programmer/HealthCheck#177]
## Feature request

-  Add a new html page for malaria disease and integrate it with malaria model present in model section. This page will take image as the input and give result .[...]

I would like to work if assigned.

**Comment by kritikaparmar-programmer** [comment]
Assigned @ayush-raj8 🚀

**Comment by ayush-raj8** [comment]
Please review and merge

**Comment by ayush-raj8** [comment]
@kritikaparmar-programmer  @utkarsh0702 please update with proper level and update my score.
