### ISSUE TITLE
Error when submitting blank form

### ISSUE THREAD

**Issue by geekymeeky** [kritikaparmar-programmer/HealthCheck#179]
## **Error when submitting blank form**

- Submitting blank form in Diabetes Prediction and Heart Disease Prediction throws an error.

## **Possible solution**

- Optimize the backend with appropriate error handling technique and provide user-friendly response.

**Comment by geekymeeky** [comment]
As a participant of GSSoC'21, I want to work on this issue.

**Comment by kritikaparmar-programmer** [comment]
Okay @geekymeeky start working on it.

**Comment by geekymeeky** [comment]
@shubhigupta991 I've already opened a PR for this issue. Kindly, review it and let me know if any change is necessary.
