### ISSUE TITLE
Tumor analysis

### ISSUE THREAD

**Issue by sudipg4112001** [kritikaparmar-programmer/HealthCheck#18]
I would like to add a project based on tumor analysis for a person. Using a dataset that would contain images of brains, then I would detect whether the person is having tumor or not.

**Comment by kritikaparmar-programmer** [comment]
Great idea @sudipg4112001, Assigned 🚀

**Comment by sudipg4112001** [comment]
I have made PR #13 which resolves both this issue and issue #12

**Comment by sudipg4112001** [comment]
I was not able to make a separate branch. So, I would link to request you to link this issue with the PR #13 so that it fulfils all the need.

**Comment by PavitraAritas** [comment]
i'm a GSSoC participant and I would like to work on this project as my first issue. Kindly assign this to me. Thankyou.

**Comment by sudipg4112001** [comment]
> i'm a GSSoC participant and I would like to work on this project as my first issue. Kindly assign this to me. Thankyou.

I have already made a PR for this issue. Kindly checkout some other issue
