### ISSUE TITLE
Enhancing the footer part

### ISSUE THREAD

**Issue by arpit456jain** [kritikaparmar-programmer/HealthCheck#185]
I would like to give it a try to make the footer more attractive .
I am a GSSoC'21 participant

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer kindly assign me this issue

**Comment by shubhigupta991** [comment]
Go ahead @arpit456jain

**Comment by arpit456jain** [comment]
@shubhigupta991 can you please merge my pr opened for issue 172 @kritikaparmar-programmer already approved my 404 page in issue section after that i had made the pr

**Comment by arpit456jain** [comment]
> @shubhigupta991 can you please merge my pr opened for issue 172 @kritikaparmar-programmer already approved my 404 page in issue section after that i had made the pr

@utkarsh0702 @shubhigupta991 @kritikaparmar-programmer

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer @shubhigupta991 @utkarsh0702 😅😅😅😅😅😅😅😅
