### ISSUE TITLE
Add a new Project : Pneumonia Detection

### ISSUE THREAD

**Issue by AM1CODES** [kritikaparmar-programmer/HealthCheck#19]
I had a project idea that i think would be suitable for this repository and would be meaningful as well. I wanted to make an addition of a model that would help in detecting Pneumonia using the chest x-ray. I have found a suitable dataset for the same and would like to work on it.

I am a GSSOC participant.

dataset - [https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia](url)

**Comment by psyduck1203** [comment]
Hey, I'm a GSSoC`21 participant and want to contribute to this repo can you please assign this issue to me?

**Comment by AM1CODES** [comment]
@psyduck1203  i am not the maintainer. I was asking @kritikaparmar-programmer if i could work on this.

**Comment by kritikaparmar-programmer** [comment]
Assigning the issue to you @AM1CODES 🚀

**Comment by kritikaparmar-programmer** [comment]
@AM1CODES updates?

**Comment by AM1CODES** [comment]
@kritikaparmar-programmer i have already made a PR few days ago. It awaits confirmation from one of the reviewers.
