### ISSUE TITLE
Flask route for Parkinson Disease

### ISSUE THREAD

**Issue by JanhaviSoni** [kritikaparmar-programmer/HealthCheck#190]
## Proposal

Flask route for Parkinson disease

**Comment by ayush-raj8** [comment]
I would like to work if assigned.

**Comment by kritikaparmar-programmer** [comment]
@JanhaviSoni assigned 👍

**Comment by kritikaparmar-programmer** [comment]
@ayush-raj8  are you willing to work on this issue?

**Comment by JanhaviSoni** [comment]
@kritikaparmar-programmer I will complete it . There is some covid related
issue . So it might take time
