### ISSUE TITLE
I want to add no.of forks,pr's, stars and other in the readme file .

### ISSUE THREAD

**Issue by srisatya1197** [kritikaparmar-programmer/HealthCheck#192]
I want to add no.of forks,pr's, stars and other in readme file .
Example:
![ss5](https://user-images.githubusercontent.com/78905067/115119007-e4bd9180-9fc3-11eb-92d0-d3443cace202.png)
I want to work on this . Please assign me this issue.

**Comment by kritikaparmar-programmer** [comment]
Assigned @srisatya1197.

**Comment by srisatya1197** [comment]
Thankyou @kritikaparmar-programmer

**Comment by srisatya1197** [comment]
@kritikaparmar-programmer I have seen the techstack in readme file should I improve them with logos?

**Comment by kritikaparmar-programmer** [comment]
Yes sure 👍 @srisatya1197

**Comment by srisatya1197** [comment]
ok thanks I'll start working on it immediately @kritikaparmar-programmer .
