### ISSUE TITLE
Determination of Tumor malignancy 

### ISSUE THREAD

**Issue by srimontidutta** [kritikaparmar-programmer/HealthCheck#198]
Determination of the malignant nature of Tumor using patient details.

**Comment by shubhigupta991** [comment]
Please provide the dataset?

**Comment by utkarsh0702** [comment]
@srimontidutta Is it similar to detecting a tumor from an image?

**Comment by srimontidutta** [comment]
> Please provide the dataset?

I have not finalized one yet.

**Comment by srimontidutta** [comment]
> @srimontidutta Is it similar to detecting a tumor from an image?

It will include the analysis of the nature of the tumor based on multiple parameters related to both the tumor and the patient.

**Comment by utkarsh0702** [comment]
@srimontidutta Please finalize dataset and if dataset will be okay, then we will assign the issue.
