### ISSUE TITLE
Determining insulin intake for diabetic.

### ISSUE THREAD

**Issue by abhish3k-11** [kritikaparmar-programmer/HealthCheck#20]
There's a diabetes dataset but it only determines if you have Diabetes or not. I think it would be a lot more helpful if we can determine the amount of insulin a diabetic person need to intake. I want to make an addition of a model that would help in same. I have found a suitable dataset for the same and would like to work on it. Please assign this issue to me.
I am a GSSOC'21 participant.

dataset - https://www.kaggle.com/peterboos/determine-insuline-intake?select=diabetic.csv
The above dataset contains less data, so I'm finding more suitable datasets for now.

**Comment by kritikaparmar-programmer** [comment]
Great Idea @abhish3k-11, assigning this issue to you.

**Comment by abhish3k-11** [comment]
@kritikaparmar-programmer thank you

**Comment by shubhigupta991** [comment]
Any Updates?

**Comment by abhish3k-11** [comment]
Model is ready. Currently searching for more data to test and train. I'll start commiting in 2-3 days at most.

**Comment by kritikaparmar-programmer** [comment]
@abhish3k-11 Updates on this issue?

**Comment by Dishita2602** [comment]
If no update I can do . Please assign me

**Comment by kritikaparmar-programmer** [comment]
@Dishita2602 assigning the issue to you.

**Comment by Dishita2602** [comment]
> @Dishita2602 assigning the issue to you.

I am unable to find suitable data set for determining insulin intake. The dataset mentioned above is too shot for predictions. Can you suggest me something better that you want to get implemented ?

**Comment by shubhigupta991** [comment]
Closing this issue then.
