### ISSUE TITLE
Improving Heart Model performance (from 78 to 92 percent accuracy)

### ISSUE THREAD

**Issue by Divyang0601** [kritikaparmar-programmer/HealthCheck#202]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

-By applying proper feature engineering technique and using StackCV Classifier model, I can drastically improve
the performance of the heart disease model

**Comment by kritikaparmar-programmer** [comment]
Assigning you @Divyang0601. Make a new .ipynb file, don't delete or edit the previous ones.
