### ISSUE TITLE
Improvement of Parkinsons Disease Model 

### ISSUE THREAD

**Issue by Borahb** [kritikaparmar-programmer/HealthCheck#205]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**
I can improve the current Parkinson's disease model by applying dimensionality reduction technique so that to increase accuracy and confusion matrix.

**Comment by utkarsh0702** [comment]
@Borahb Have you tried using dimensionality reduction?

**Comment by Borahb** [comment]
@utkarsh0702  Yaa I have tried dimensionality reduction.

**Comment by utkarsh0702** [comment]
@Borahb What was the accuracy?

**Comment by Borahb** [comment]
@utkarsh0702  Accuracy came above 95% ,  close to 96 or 97.

**Comment by utkarsh0702** [comment]
@Borahb Create a pr.
