### ISSUE TITLE
Skin cancer prediction

### ISSUE THREAD

**Issue by mansi75** [kritikaparmar-programmer/HealthCheck#209]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by mansi75** [comment]
https://www.kaggle.com/kmader/skin-cancer-mnist-ham10000
Kindly, assign me this project

**Comment by utkarsh0702** [comment]
@mansi75 The dataset contains text. Can we really predict skin cancer without image data.
