### ISSUE TITLE
Add Code Of Conduct 

### ISSUE THREAD

**Issue by Akash20x** [kritikaparmar-programmer/HealthCheck#21]
I want to add code of conduct in your repo.
Please assign me this task as a part of GSSoC'21

**Comment by kritikaparmar-programmer** [comment]
Hey, @Akash20x haven't you joined the official GSSOC'21 discord channel, all the participants are provided with the link.
Still, if you want to contact me, here is my email address - kritikaparmar07@gmail.com
you can also contact me on Linkedin - https://www.linkedin.com/in/kritika-parmar-10244a193/

**Comment by Akash20x** [comment]
OK, I will include it in Code of conduct
