### ISSUE TITLE
Improving the Liver Model to  98+ accuracy

### ISSUE THREAD

**Issue by Divyang0601** [kritikaparmar-programmer/HealthCheck#211]
## **Is your feature request related to a problem? Please describe.**

WIth proper data analysis, I intend to improve the performance of the liver model

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.

**Comment by Divyang0601** [comment]
Pls assign this issue

**Comment by Borahb** [comment]
Can I work on this issue? @utkarsh0702

**Comment by utkarsh0702** [comment]
Ok

**Comment by Borahb** [comment]
@utkarsh0702  no I was not assigned this issue. As this issue was stale , I thought of asking you to assign it me.

**Comment by utkarsh0702** [comment]
@Borahb I have already assigned you the issue. Please create a pr within 2 days otherwise, I have to close this issue.

**Comment by Borahb** [comment]
@utkarsh0702  I have tried for achieving 98 but I could only get up to  74
