### ISSUE TITLE
Diabetes Prediction 

### ISSUE THREAD

**Issue by Manasi2001** [kritikaparmar-programmer/HealthCheck#212]
Although some analysis has been done on the topic, but I would like to include some more concepts like VIF and outliners checking in my notebook and will use Logistic Regression. They'll allow to filter out the dirty data that creeps in, hence boosting the accuracy. I would like to work on this under GSSoC'21. Please assign it to me.

**Comment by Manasi2001** [comment]
@kritikaparmar-programmer please assign the issue :)

**Comment by utkarsh0702** [comment]
@Manasi2001 Assigning it to you
