### ISSUE TITLE
Covid19 CT images.

### ISSUE THREAD

**Issue by barnamensch056** [kritikaparmar-programmer/HealthCheck#214]
## **Is your feature request related to a problem? Please describe.**

- I will like to generate a model to predict the Covid19 using  CT images. 
## **Describe the solution you'd like**

-  CT scans give more imaging features in predicting Covid19 and moreover if in future a flask route can be created for testing covid report using both x-rays and CT scans :).

**Comment by barnamensch056** [comment]
@kritikaparmar-programmer can you assign to this issue?

**Comment by utkarsh0702** [comment]
@barnamensch056 please provide link to the dataset.

**Comment by barnamensch056** [comment]
https://www.kaggle.com/luisblanche/covidct  here is the link.

**Comment by utkarsh0702** [comment]
@barnamensch056 Assigning it to you.

**Comment by barnamensch056** [comment]
Thsnks @utkarsh0702 👍
