### ISSUE TITLE
Addition of Breast Cancer Detection Model

### ISSUE THREAD

**Issue by Borahb** [kritikaparmar-programmer/HealthCheck#219]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- I think it would be great if breast cancer detection model is also added, as there already different models predicting different diseases.
- I can make the prediction model with a good accuracy.

**Comment by Borahb** [comment]
@utkarsh0702  Can I work on this issue ?

**Comment by utkarsh0702** [comment]
@Borahb Please create the liver model pr first, then I will assign it to you.

**Comment by Borahb** [comment]
@utkarsh0702  can you open this issue,  can make the PR by morning.

**Comment by utkarsh0702** [comment]
@Borahb Create the pr by today.

**Comment by Borahb** [comment]
@utkarsh0702  made the PR
