### ISSUE TITLE
Parkinson flask route

### ISSUE THREAD

**Issue by JanhaviSoni** [kritikaparmar-programmer/HealthCheck#225]
## Proposal

I would like to add flask route for Parkinson disease.

**Comment by kritikaparmar-programmer** [comment]
Ok @JanhaviSoni go ahead

**Comment by JanhaviSoni** [comment]
@kritikaparmar-programmer @shubhigupta991 I have got some error . While running app.py in conda it says tensorflow.keras.models import load_model not found though keras and tensorflow both are installed

**Comment by utkarsh0702** [comment]
@JanhaviSoni Please create the PR by tomorrow.
