### ISSUE TITLE
Kidney stone prediction

### ISSUE THREAD

**Issue by manisha-27** [kritikaparmar-programmer/HealthCheck#228]
Detection of Kidney stone in the Ultrasound and CT scan images using Image processing and Machine Learning.

**Comment by utkarsh0702** [comment]
@manisha-27 You opened the issue 12 hour back, nobody assigned it to you and then you opened a pr just after an hour.
I am assigning you the issue for the last time. Please don't do this kind of work again, it's against the code of conduct.
