### ISSUE TITLE
addition of issue and pr templates

### ISSUE THREAD

**Issue by Sloth-Panda** [kritikaparmar-programmer/HealthCheck#23]
This repo lacks issue and pr templates so would like to add them as part of gssoc'21

**Comment by Sloth-Panda** [comment]
@kritikaparmar-programmer should I get this done. It will help you get ideas about your issues and prs better.

**Comment by shubhigupta991** [comment]
You can start working on it. @Sloth-Panda

**Comment by Sloth-Panda** [comment]
@shubhigupta991 can you please add "level0/ level1/ level2/ level3" any of the tags to the issue and pr along with "gssoc21"as per gssoc guidelines
else they wont be counted
