### ISSUE TITLE
Adding Malaria Detection

### ISSUE THREAD

**Issue by NitiKaur** [kritikaparmar-programmer/HealthCheck#26]
We can also add Malaria detection as an issue in this repo.Millions of people in India and other developing countries suffer from the disease. We can detect the malarial parasite in the image of a blood cell.
I have found a dataset for the same - https://drive.google.com/file/d/1azIYjzLFCY7qp7-NjgSBvakbGgPvQlRf/view  . I want to use feature extraction techniques such as contour detection and then use Random Forest Classifier. If found suitable please make this an issue and assign it to me

**Comment by kritikaparmar-programmer** [comment]
Hey @NitiKaur I've already implemented Malaria detection you can take a look at notebooks, and then tell me that is there something else you can do, Actually model for malaria detection is ready only making API is left. So do tell what's your suggestion on this :)

**Comment by NitiKaur** [comment]
Don'r know anything about APIs but there is a hack thru which we can display the results of the model on the webpage. The hack is using a python library.Can I work on the hack?
