### ISSUE TITLE
Lung Disease

### ISSUE THREAD

**Issue by gopichandpuli9** [kritikaparmar-programmer/HealthCheck#28]
Can I work on this issue.

**Comment by kritikaparmar-programmer** [comment]
Can you please provide a bit more details on this, like the dataset.

**Comment by gopichandpuli9** [comment]
https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia 
This is the dataset I want to work.

**Comment by kritikaparmar-programmer** [comment]
Hey, @gopichandpuli9 the same issue has already been opened by someone, you can look into the issues. Please take a look at the existing issues before opening 😅

**Comment by gopichandpuli9** [comment]
I've gone through the issues. But there's no one who implemented Lung disorder.

**Comment by kritikaparmar-programmer** [comment]
Hey @gopichandpuli9 Take a look at #19
