### ISSUE TITLE
Parkinson's Disease Prediction

### ISSUE THREAD

**Issue by JanhaviSoni** [kritikaparmar-programmer/HealthCheck#32]
@kritikaparmar-programmer I would like to add Parkinson's disease prediction project for GSSoC'21
(https://www.kaggle.com/nidaguler/parkinsons-data-set)

**Comment by shubhigupta991** [comment]
You can start working on it. @JanhaviSoni

**Comment by JanhaviSoni** [comment]
I had a doubt regarding setting up of project @shubhigupta991 that this will get set up in Jupyter notebook itself , no extra aids will be required na?
