### ISSUE TITLE
Adding Cervical Cancer prediction to your Cancer Notebook

### ISSUE THREAD

**Issue by NitiKaur** [kritikaparmar-programmer/HealthCheck#33]
Hey! I wish to solve this issue faced by women. I will be using four algorithms
1.CNN
2.KNN
3.XGBoost
4.Random trees
I will be also using Ensemble methods if need be
Please assign this issue to me

**Comment by shubhigupta991** [comment]
You can start working on it. @NitiKaur

**Comment by Dishita2602** [comment]
Hello, I would willing to contribute to this project. I would be using hyperparameter tuning for decision tree, multilayer perceptron SVM, ANN and many more to get better results.

**Comment by shubhigupta991** [comment]
This issue is already assigned to @NitiKaur you can open a different issue

**Comment by Dishita2602** [comment]
> This issue is already assigned to @NitiKaur you can open a different issue

Thanks for informing

**Comment by shubhigupta991** [comment]
Any Updates @NitiKaur

**Comment by kritikaparmar-programmer** [comment]
@NitiKaur I think you've been provided with more than enough time, so unassigning you.
@Dishita2602 Would you like to work on this issue?

**Comment by Dishita2602** [comment]
> @NitiKaur I think you've been provided with more than enough time, so unassigning you.
> @Dishita2602 Would you like to work on this issue?

yes

**Comment by kritikaparmar-programmer** [comment]
Ok @Dishita2602 assigning this issue to you. Happy Coding :)

**Comment by manan-bedi2908** [comment]
@Dishita2602 Hi, kindly create a new branch in this repo and create a pr by pushing the changes to that newly created branch. 
We will then merge it

**Comment by Dishita2602** [comment]
> @Dishita2602 Hi, kindly create a new branch in this repo and create a pr by pushing the changes to that newly created branch.
> We will then merge it

Alright !

**Comment by Dishita2602** [comment]
> @Dishita2602 Hi, kindly create a new branch in this repo and create a pr by pushing the changes to that newly created branch.
> We will then merge it

I have made pull request Cervic_Risk_#33 #183 kindly review it.
