### ISSUE TITLE
Infectious Diseases

### ISSUE THREAD

**Issue by aakriti1318** [kritikaparmar-programmer/HealthCheck#38]
Hey, I am a GSSOC'21 participant
I would like to add a project based on infectious diseases. This will basically predict how several diseases affect gender, and which disease affects which particular area most over time. 
I have found the associated dataset: https://www.kaggle.com/rishidamarla/infectious-diseases-by-american-counties

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant. I have worked on a similar problem before and would like to contribute to this issue. Kindly consider assigning me this issue under GSSOC'21.

**Comment by kritikaparmar-programmer** [comment]
Hey, this dataset contains only Califonia's stats, as we can't be specific to any place so can't add this to our project, closing this issue for now :)
