### ISSUE TITLE
Visualizing loss and accuracy metric in Malaria detection 

### ISSUE THREAD

**Issue by HimanchalChandra** [kritikaparmar-programmer/HealthCheck#4]
I want to implement visualizations for loss and accuracy metric in malaria detection model. Can you please assign it to me?, I am a participant of GSSOC'21.

**Comment by kritikaparmar-programmer** [comment]
Hey, @HimanchalChandra assigning this issue to you. Don't forget to submit the pr only when the contribution period of GSSOC'21 starts. Happy Coding :)

**Comment by kritikaparmar-programmer** [comment]
@HimanchalChandra updates?
