### ISSUE TITLE
Pancreatic Cancer Prediction Using 5 Different Algorithms with  Hyperparameters Optimization.

### ISSUE THREAD

**Issue by ritikkumar55** [kritikaparmar-programmer/HealthCheck#40]
I want to add the some more algorithms which is used to predict if users suffer from Cancer or not.
The classification models which we will use  and will do some Hyperparameters optimizations are: 
1. Logistic Regression
2. Decision Tree Classifier
3. XGBClassifier
4. CatBoostClassifier
5. LGBMClassifier

I am a GSSOC'21 participant
Please assign me  these tasks. @kritikaparmar-programmer

**Comment by kritikaparmar-programmer** [comment]
Can you please provide the dataset @ritikkumar55

**Comment by ritikkumar55** [comment]
> Can you please provide the dataset @ritikkumar55

Dataset Link : https://www.kaggle.com/loveall/cervical-cancer-risk-classification

**Comment by shubhigupta991** [comment]
Assigned @ritikkumar55

**Comment by ritikkumar55** [comment]
Thank you @shubhigupta991

**Comment by shubhigupta991** [comment]
Any Updates ?

**Comment by ritikkumar55** [comment]
> Any Updates ?

Almost Done @shubhigupta991 Tomorrow I will submit it.

**Comment by shubhigupta991** [comment]
okay

**Comment by Dishita2602** [comment]
I would like to work on this if no updates
