### ISSUE TITLE
Complete data Visualization for heart disease prediction

### ISSUE THREAD

**Issue by mansi75** [kritikaparmar-programmer/HealthCheck#43]
I am GSSOC 2021 participant, please kindly assign me this issue under GSSOC 2021.
I will do the complete visualization of the data and thorough explaination of the plots and data using various visualization libraries.

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant. I want to contribute to this issue. I will visualize complex data in a simple way. I would use various visualization libraries like Matplotlib and Seaborn and would explain my plots in detail. Kindly assign me this issue under GSSOC'21.

**Comment by Sibasish-Padhy** [comment]
hiiii....I am a gssoc 2021 participant,I want to  contribute to this issue.I can do the complete data visulaization and thorough explanation of the plots and data in python

**Comment by kritikaparmar-programmer** [comment]
Okk @mansi75 you can to exploratory data analysis of heart data, make a new notebook in the notebooks folder named - eda_heart. Happy Coding :)

**Comment by mansi75** [comment]
@kritikaparmar-programmer 
Kindly review my pull request
https://github.com/kritikaparmar-programmer/HealthCheck/pull/103

**Comment by mansi75** [comment]
@kritikaparmar-programmer 
Kindly check my PR

**Comment by kritikaparmar-programmer** [comment]
Closing this issue as pr #140 is merged.
