### ISSUE TITLE
Add a new project: Cervical cancer risk classification

### ISSUE THREAD

**Issue by mansi75** [kritikaparmar-programmer/HealthCheck#44]
This is a good project that can be added. It's dataset is given below

https://www.kaggle.com/loveall/cervical-cancer-risk-classification

I am a GSSOC 2021 participant. Please kindly assign me this issue.

**Comment by Rutikab12** [comment]
Hey I am GSSoC'21 participant, I will love to contribute to this issue. If possible assign it to me.

**Comment by kritikaparmar-programmer** [comment]
@mansi75 I've assigned you one issue, first work on that :)

**Comment by Rutikab12** [comment]
> @mansi75 I've assigned you one issue, first work on that :)

Yeah working on it. I had comment it before that issue. Excuse me for bothering you .

**Comment by rayushbpgc** [comment]
Hi, I'm am participant, I would like to work on this project. Please assign me.

**Comment by Dhanush2612** [comment]
@kritikaparmar-programmer @utkarsh0702 
Hi, can you kindly  assign me this issue?

**Comment by shubhigupta991** [comment]
Any updates @mansi75

**Comment by kritikaparmar-programmer** [comment]
@Dhanush2612 would you like to work on this issue?

**Comment by mansi75** [comment]
> Any updates @mansi75

@kritikaparmar-programmer Sorry, ma'am for replying late but I am working on the same. I was working on increase the accuracy of the model, so got late a bit.

**Comment by Dhanush2612** [comment]
@kritikaparmar-programmer 
I would like to work on the issue

**Comment by kritikaparmar-programmer** [comment]
Okay, @mansi75 we understand but if you're working on the issue just give us the updates. So I'm giving you 3 days max as we are asked for giving 5 days max. So please try to make a pr within 3 days.

**Comment by mansi75** [comment]
@kritikaparmar-programmer 
https://github.com/kritikaparmar-programmer/HealthCheck/pull/153
Pull request generated, kindly check
