### ISSUE TITLE
 Thyroid Disease Data Prediction

### ISSUE THREAD

**Issue by aishwaryachand** [kritikaparmar-programmer/HealthCheck#47]
hey @kritikaparmar-programmer 
I would like to contribute to this repo by working on  model  for thyroid Disease Classification.  I will use some Hyperparameters optimizations as well.
This will be the data that i will be referring to .
https://archive.ics.uci.edu/ml/datasets/Thyroid+Disease

I am a GSSOC'21 participant
Please assign me these tasks.

**Comment by kritikaparmar-programmer** [comment]
@aishwaryachand assigning you the issue. Make a new notebook in the notebooks folder named - Thyroiddisease

**Comment by shubhigupta991** [comment]
Any updates?

**Comment by utkarsh0702** [comment]
@aishwaryachand Please provide update regarding the issue.

**Comment by aishwaryachand** [comment]
Sorry for the late response ... I am just working with different models . Just give me a couple of days more. Unfortunately I was buzy with exams. So started a  bit late.

**Comment by shubhigupta991** [comment]
Finish within 2 days because its already 18 days.

**Comment by kritikaparmar-programmer** [comment]
@aishwaryachand Updates?

**Comment by sakshi012000** [comment]
@kritikaparmar-programmer  I am a GSSoC participant can you please assign me this?

**Comment by utkarsh0702** [comment]
@sakshi012000 Assigning it to you.

**Comment by sakshi012000** [comment]
@utkarsh0702  I have made a PR please check it. PR: #161

**Comment by sakshi012000** [comment]
@utkarsh0702 Please check my updated PR. PR: #161
