### ISSUE TITLE
Oral Cancer Detection 

### ISSUE THREAD

**Issue by noobkid2411** [kritikaparmar-programmer/HealthCheck#48]
This seems to be a relevant sub project  for this project. I would like to work on it. 

Here is the source of the dataset I will use:
https://www.sciencedirect.com/science/article/pii/S2352340920300081?via%3Dihub

I am a GSSOC'21 Participant.

**Comment by shubhigupta991** [comment]
Go ahead @noobkid2411

**Comment by shubhigupta991** [comment]
Any updates?

**Comment by noobkid2411** [comment]
Hi,sorry for not updating beforehand,I'm having some issues with the data size and the images,I'm trying to change the dataset and create a model. Really sorry for not updating before.

**Comment by shubhigupta991** [comment]
Okay so how much time you need? because its already 15days after assigning.

**Comment by noobkid2411** [comment]
I'll definitely make a pr by this weekend,,if that's okay .I'm sorry I could not deliver on time.

**Comment by noobkid2411** [comment]
@shubhigupta991 hi I'm sorry but I won't be able to create a pr as I'm having some trouble processing the data on my machine as of now,I'm trying to clear it up,but if its okay,you could unassign me. I'm really sorry for the inconvenience caused.

**Comment by shubhigupta991** [comment]
okay

**Comment by Anas-Issa** [comment]
I am a gssoc'21 participant.I would like to work on this issue if possible.
Oral Cancer (Lips and Tongue) images Dataset: [Here](https://www.kaggle.com/shivam17299/oral-cancer-lips-and-tongue-images)

**Comment by shubhigupta991** [comment]
Assigned @Anas-Issa

**Comment by kritikaparmar-programmer** [comment]
Closing this issue as #141 pr is merged :)
