### ISSUE TITLE
Complete Data Preprocessing, Data Visualisation, Model Selection and Hyperparameter Tuning on Diabetes Disease prediction 

### ISSUE THREAD

**Issue by shreyasZ10** [kritikaparmar-programmer/HealthCheck#49]
I am a participant of GSSOC'21.
I would like to make some enhancement in the DiabetesNotebook.ipynb.
1) Adding Data Preprocessing
2) Data Visualisation
3) Model Selection
4) Hyperparameter Tuning

**Comment by Dishita2602** [comment]
Hello, I am GSSOC'21 participant and want to work on all the above mentioned issue in efficient manner.

**Comment by shubhigupta991** [comment]
Go ahead @shreyasZ10
