### ISSUE TITLE
Data Visualization of cancer, fetal_health, diabetes, india_liver_patient & heart

### ISSUE THREAD

**Issue by Dishita2602** [kritikaparmar-programmer/HealthCheck#50]
Hey, I will be using seaborn, matplotlib and dtale library for performing exploratory data analysis & find optimum combination of features for prediction (i.e. correlation coeff & many more). Data visualization is essential in medical for detail case study. So kindly assign me !

**Comment by shubhigupta991** [comment]
Assigned @Dishita2602
