### ISSUE TITLE
Prediction of india_liver_patient

### ISSUE THREAD

**Issue by Dishita2602** [kritikaparmar-programmer/HealthCheck#51]
Hey, I will use hyperparameter tuning for getting optimized results. I will use SVM ,Decision Tree, XG Boost, MLP, Logistic regression and random forest. Kindly assign me. ( Currently GSSOC'21 Participant )

**Comment by kritikaparmar-programmer** [comment]
Hey @Dishita2602 we can't be just specific to one place, thus can't add this to our project for now. I'll be opening some new issues keep an eye on them
