### ISSUE TITLE
wrong instruction on README.md

### ISSUE THREAD

**Issue by flyingsonu122** [kritikaparmar-programmer/HealthCheck#53]
this will create authorization issue while adding changes

![image](https://user-images.githubusercontent.com/51280276/110866136-b1178980-82ea-11eb-9694-374100a6f46b.png)

it should be like this 🔽 

![image](https://user-images.githubusercontent.com/51280276/110866752-a4dffc00-82eb-11eb-8159-63e575dd6353.png)

I can add **more changes** to it as well

**Comment by flyingsonu122** [comment]
@kritikaparmar-programmer please have a look and assign it to me

**Comment by Srijan205** [comment]
i would like to work on this issue

**Comment by flyingsonu122** [comment]
> i would like to work on this issue

already I am working on it
