### ISSUE TITLE
No matching distribution found for scikit-learn==0.21.1

### ISSUE THREAD

**Issue by flyingsonu122** [kritikaparmar-programmer/HealthCheck#55]
should be like this 
![image](https://user-images.githubusercontent.com/51280276/110870917-651d1280-82f3-11eb-9f68-2d9716d239c5.png)

**Comment by sujoy-coder** [comment]
Hey @flyingsonu122 , I think there is problem with the scikit-learn version ==0.21.1 
Therefore we need to upgrade the scikit-learn version to latest version like 0.24.1

**Comment by flyingsonu122** [comment]
> Hey @flyingsonu122 , I think there is problem with the scikit-learn version ==0.21.1
> Therefore we need to upgrade the scikit-learn version to latest version like 0.24.1

That is what I have done already, see in the screenshot

**Comment by flyingsonu122** [comment]
Already created a PR #57 for the same @kritikaparmar-programmer

**Comment by sujoy-coder** [comment]
Ok.. I have closed #59

**Comment by kritikaparmar-programmer** [comment]
Hey @flyingsonu122 take a look at this issue - https://github.com/kritikaparmar-programmer/HealthCheck/issues/5

**Comment by flyingsonu122** [comment]
> Hey @flyingsonu122 take a look at this issue - #5

Just merge my PR it will fix this issue

**Comment by flyingsonu122** [comment]
@kritikaparmar-programmer what are you waiting for

**Comment by kritikaparmar-programmer** [comment]
@flyingsonu122 First of all in Open Source you are not allowed to make a pr until you're assigned with the issue, and second is that if you've taken a look in the issue I said then it will explain you why the scikit learn version is not 0.24, I pickled the model in version 0.21 and we can't unpickle the model in different version as the version 0.21.1 is supported by python 3.7

**Comment by flyingsonu122** [comment]
but 0.21 is not working

**Comment by kritikaparmar-programmer** [comment]
What is the version of python on your local system @flyingsonu122

**Comment by flyingsonu122** [comment]
3.8.3

**Comment by flyingsonu122** [comment]
Whole world is using python 3.9.2 and you are on 3.5-3.7

Atleast make it compatible with 3.8.x

@kritikaparmar-programmer

**Comment by kritikaparmar-programmer** [comment]
Okay, I've started working on it. Closing this issue for now
