### ISSUE TITLE
No module named 'sklearn.ensemble.forest'

### ISSUE THREAD

**Issue by flyingsonu122** [kritikaparmar-programmer/HealthCheck#58]
![image](https://user-images.githubusercontent.com/51280276/110871939-5afc1380-82f5-11eb-99b3-90bbf693678e.png)

**Comment by kritikaparmar-programmer** [comment]
Just rerun the notebooks in your local system, I think that will fix this issue.

**Comment by aelbasioni** [comment]
I have a similar error message "ModuleNotFoundError: No module named 'sklearn.ensemble._forest'". I'm using python 3.7.0 I don't know what to do to solve it. Please more clarification because I'm very new to python & AI world
