### ISSUE TITLE
New Route in flask app for Fetal Health Classification

### ISSUE THREAD

**Issue by sujoy-coder** [kritikaparmar-programmer/HealthCheck#60]
Hey @shubhigupta991 @kritikaparmar-programmer , I want to contribute on this issue as a participant of GSSOC'21. modification in `app.py`

Please assign it to me 🙏

Thank You...

**Comment by shubhigupta991** [comment]
What type of modification you want to make?

**Comment by sujoy-coder** [comment]
There is already a pretrain **Fetal Health** model. I just want to use that model in flask app by creating a new route in `app.py` just like diabetes and cancer route which area there in app.py.

Thank You...

**Comment by shubhigupta991** [comment]
Go ahead @sujoy-coder

**Comment by sujoy-coder** [comment]
Ok... Thnx
