### ISSUE TITLE
beautify predicted h_result.html page

### ISSUE THREAD

**Issue by sujoy-coder** [kritikaparmar-programmer/HealthCheck#62]
HI, I want to contribute on this issue as a participant of GSSOC'21.

#### Modifications 
1. Place html Footer to its proper position
2. Add Interactive Output Text in one line ...
 
etc...

Please assign it to me...

Thank You....

#### Existing Page Looks Like :
![Screenshot (17)](https://user-images.githubusercontent.com/65298629/110901208-f6a77700-8329-11eb-8dcc-849b158dcb98.png)

**Comment by kritikaparmar-programmer** [comment]
@sujoy-coder great idea, you can implement this once you complete your one assigned issue.

**Comment by sujoy-coder** [comment]
@kritikaparmar-programmer My previously assigned issue has been completed which is also merged with main branch of this project. 
Can I start working this issue ?

**Comment by shubhigupta991** [comment]
yes

**Comment by sujoy-coder** [comment]
@shubhigupta991 the forms for prediction is not looking good, may I add some css for make it good looking ?

**Comment by kritikaparmar-programmer** [comment]
@sujoy-coder go ahead 👍
