### ISSUE TITLE
bugs in CONTRIBUTING.md

### ISSUE THREAD

**Issue by sujoy-coder** [kritikaparmar-programmer/HealthCheck#65]
HI @shubhigupta991  , I want to contribute on this issue as a participant of GSSOC'21.
I find an error in `CONTRIBUTING.md` that is Highlighted in the picture :

![Screenshot (18)](https://user-images.githubusercontent.com/65298629/110929588-1a7cb400-834e-11eb-8a9c-0a1e5c6b6747.png)

**The Problem is `origin` remote is not set there before pushing to origin we must set the origin remote link, like :** 
`git remote add origin https://github.com/<your-github-username>r/HealthCheck`

Please assign it to me 🙏

**Comment by Srijan205** [comment]
i would like to work on this issue

**Comment by kritikaparmar-programmer** [comment]
Hey, @sujoy-coder never open a pr, until you're assigned for the issue or until any mentor reviews the pr.

**Comment by sujoy-coder** [comment]
My bad..
What should I do now?

**Comment by kritikaparmar-programmer** [comment]
This issue was already assigned to someone and that or is also merged, so closing this PR for now.
