### ISSUE TITLE
Automatic Contributor update

### ISSUE THREAD

**Issue by rohank2502** [kritikaparmar-programmer/HealthCheck#67]
I will like to add a feature which will update the contributor list automatically will start work on this issue as soon as I get assigned !

**Comment by kritikaparmar-programmer** [comment]
Which contributor list you want to update @rohank2502

**Comment by rohank2502** [comment]
> 
> 
> Which contributor list you want to update @rohank2502

I will like to include the contributor list in read me

**Comment by kritikaparmar-programmer** [comment]
Okay @rohank2502, start working on the issue.
