### ISSUE TITLE
Missing command in CONTRIBUTING.md

### ISSUE THREAD

**Issue by sujoy-coder** [kritikaparmar-programmer/HealthCheck#73]
Hey @kritikaparmar-programmer , There is a missing command in `CONTRIBUTING.md` file, marked in the **picture** . After forked the repo how to clone the repo in my local computer.
I want to add that line..
Please assign it to me 🙏  

### Picture 

![Screenshot (29)](https://user-images.githubusercontent.com/65298629/111022419-9df2df80-83f8-11eb-9e10-50e7fa0d7ed9.png)

**Comment by kritikaparmar-programmer** [comment]
@sujoy-coder This is already implemented in Readme.md, also if you're assigned for one issue then don't ask for another until it's completed. Thanks :)
