### ISSUE TITLE
Notebook on COVID 19 Prediction of Total Confirmed Cases in India 

### ISSUE THREAD

**Issue by Dishita2602** [kritikaparmar-programmer/HealthCheck#75]
Hey, I have done prediction with 99% accuracy using SVR, Naive Bayes Regression, Random Forest and Polynomial Regression. So if you want to add this project kindly assign me.

**Comment by utkarsh0702** [comment]
@Dishita2602 As you know we are building a website, so definetly we won't have a need for nootbooks, but still we are keeping important ones to get reference.
Sorry but we currwntly don't have any need for visualizations and COVID predictions.
I request you to close the issue and come up with a great idea and create a new issue or if you want you can take the issues labeled as Up for Grab.
