### ISSUE TITLE
EDA, Modelling using DNN of Heart Attack Possibility.

### ISSUE THREAD

**Issue by barnamensch056** [kritikaparmar-programmer/HealthCheck#77]
1.Data analysis using pandas.
2.Data visualization using matplotlib and seaborn.
3.Modelling ANN with keras and tensorflow.
4.Evaluating the model.
5.Storing the model in pickle file.

**Comment by shubhigupta991** [comment]
What extra features you think are missing in the existing notebook and you can provide?

**Comment by barnamensch056** [comment]
Have done univariate analysis and bivariate analysis. Also detected the outliers and modelled it using dense neural network.
