### ISSUE TITLE
Create Code of Conduct

### ISSUE THREAD

**Issue by muthuannamalai12** [kritikaparmar-programmer/HealthCheck#89]
I would like to add a code of conduct file as the code of conduct is a necessary file which the contributors need to follow so that everyone follows a decorum.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Girl Script Summer Of Code. Kindly assign it to me.

**Comment by kritikaparmar-programmer** [comment]
Already implemented @muthuannamalai12, please firsts take a look at already implemented issues or pr's. Closing this issue.
