### ISSUE TITLE
Updation in Readme.md 

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [kritikaparmar-programmer/HealthCheck#9]
There will be many first-time contributors to the repository, update the readme.md file with proper instructions and screenshots on how they can make their first step towards Open Source.

**Comment by aayushibansal2001** [comment]
Hi! I want to work on this issue. Can you please assign it to me?

**Comment by kritikaparmar-programmer** [comment]
Assigned to you @aayushibansal2001 🚀

**Comment by aayushibansal2001** [comment]
Thanks for assigning the issue! Can you please add GSSOC label to it so that it counts as a contribution under GSSOC'21?

**Comment by rohank2502** [comment]
I will like to add the tech stack used in this project in read me

**Comment by Nishayadav-bit** [comment]
Hey @kritikaparmar-programmer , I'm a GSSOC'21 participant .
I would like to work on this issue, Please assign to me.

**Comment by kritikaparmar-programmer** [comment]
Hey @Nishayadav-bit this issue is open to all, just comment on the changes you want to do and a mentor will approve the change then you can directly create a pr.

**Comment by anirudhsai20** [comment]
Hi! There are a lot of grammatical errors in the Readme file that I would like to correct. Please assign this issue to me under GSSOC.

**Comment by srisatya1197** [comment]
Hello sir/ma'am I want to add no.of forks, stars, pr's and other in readmefile.
Like:
![ss5](https://user-images.githubusercontent.com/78905067/115119109-5eee1600-9fc4-11eb-8656-26fd7942e714.png)
