### ISSUE TITLE
Result page for Fetal Health prediction not working

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [kritikaparmar-programmer/HealthCheck#90]
## **Describe the bug**
Result page for Fetal Health prediction not working

## **Screenshots**
![Screenshot 2021-03-15 144535](https://user-images.githubusercontent.com/59971890/111130674-7ee18280-859d-11eb-928b-82ec3118df06.png)

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by shubhigupta991** [comment]
yes go ahead @AshuKV

**Comment by kritikaparmar-programmer** [comment]
Updates @AshuKV ?

**Comment by kritikaparmar-programmer** [comment]
I'm closing this issue as the page is working fine now.
