### ISSUE TITLE
Making homepage for the project more attractive

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [kritikaparmar-programmer/HealthCheck#91]
## **Is your feature request related to a problem? Please describe.**
Making the homepage for the project more attractive. Right now the home page is dull.

![Screenshot 2021-03-15 145233](https://user-images.githubusercontent.com/59971890/111131727-8d7c6980-859e-11eb-94b7-421cf8a90323.png)

**Comment by HOTSONHONET** [comment]
@kritikaparmar-programmer I'm a GSSOC'21 participant and I would like to work on this issue. If assigned my plan is to use python -dash served over flask to make the homepage more like an interactive dashboard. If you like the idea, please assign this issue to me

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by Ayushisood** [comment]
@kritikaparmar-programmer Hey ,Can I work on this issue under GSSOC'21
Will make the homepage more attractive using bootstrap.

**Comment by kritikaparmar-programmer** [comment]
@HOTSONHONET assigning you the issue. Go ahead 🚀

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer there is a **help wanted** tag what does it means??
Can I work on it too ?

**Comment by Inventor77** [comment]
@kritikaparmar-programmer Please mam let me work on this Issue I will soon present some mock ups after get assigned and as it get approved I will start working on it

**Comment by HOTSONHONET** [comment]
> @HOTSONHONET assigning you the issue on the basis of first come first serve. Go ahead 🚀

thanks ma'am

**Comment by kritikaparmar-programmer** [comment]
@HOTSONHONET it's been more than 7 days and you've not made any or, or updated us, are u still working on this issue?

**Comment by arpit456jain** [comment]
> @HOTSONHONET it's been more than 7 days and you've not made any or, or updated us, are u still working on this issue?

I would like to work on this under GSSoC'21

**Comment by ayush-raj8** [comment]
> @HOTSONHONET it's been more than 7 days and you've not made any or, or updated us, are u still working on this issue?

I would like to work and have ideas to make front page better , if assigned.

**Comment by Inventor77** [comment]
@kritikaparmar-programmer Please mam assign me this Issue

**Comment by kritikaparmar-programmer** [comment]
@arpit456jain assigning this issue to you on the basis of first come first serve.

**Comment by arpit456jain** [comment]
Ok @kritikaparmar-programmer .

Kindly review my open Pr for footer enhancement

**Comment by arpit456jain** [comment]
@kritikaparmar-programmer kindly review my PR

**Comment by arpit456jain** [comment]
<img width="934" alt="footer" src="https://user-images.githubusercontent.com/55352601/116810397-2e2fe400-ab61-11eb-9be7-ab2222f44e51.png">

@kritikaparmar-programmer I have made this footer check if its suits to you if yes I can make a Pr for this if no then no problem

**Comment by SpecTEviL** [comment]
@kritikaparmar-programmer Is this project hosted somewhere so that I can see the Homepage and if possible work on this issue?

**Comment by subhangi2731** [comment]
If no one is working on this issue can I work @kritikaparmar-programmer

**Comment by SpecTEviL** [comment]
> @kritikaparmar-programmer Is this project hosted somewhere so that I can see the Homepage and if possible work on this issue?
Awaiting your reply @kritikaparmar-programmer. If this issue isn't active do let us know that. Thanks!

**Comment by earnsans** [comment]
hii, I'm a GSSOC'21 participant, I can make this homepage attractive, could you please assign this issue to me @kritikaparmar-programmer
