### ISSUE TITLE
ANN for the Cancer Prediction

### ISSUE THREAD

**Issue by AryaPatel1111** [kritikaparmar-programmer/HealthCheck#93]
## **Added the ANN**

- I have added a ANN in the Cancer prediction which involves 4 layers which involves 3 hidden layer and was able to achieve 97.36% accuracy. It includes use of TensorFlow and confusion matrix.
- I would like to create a pull request if accepted.

**Comment by shubhigupta991** [comment]
You should not create a PR until you are assigned with the issue. I am reviewing your PR this time. Next time it will not be accepted.

**Comment by AryaPatel1111** [comment]
I had contacted @utkarsh0702 via email and asked about it.  He asked me create a PR
