### ISSUE TITLE
Binary file not found

### ISSUE THREAD

**Issue by JanhaviSoni** [kritikaparmar-programmer/HealthCheck#95]
## **Binary file not found **

The models folder doesn't have any file for Pneumonia detection thought the file is generated in the code but it is missing in models folder

## **Need to add the generated file**

- Running code and generating.

@kritikaparmar-programmer Please look into this

**Comment by utkarsh0702** [comment]
@JanhaviSoni The model was build using transfer learning, so the model is bigger in size and is stored in a shared drive folder.
