### ISSUE TITLE
Diabetes Classification using Neural Network 

### ISSUE THREAD

**Issue by Dhanush2612** [kritikaparmar-programmer/HealthCheck#96]
A neural network using Keras that classifies risk for diabetes based on health data.

**Comment by Dhanush2612** [comment]
@kritikaparmar-programmer can you suggest me any other model that can be implemented in this project?

**Comment by utkarsh0702** [comment]
@Dhanush2612 An issue and pr regarding this has already been merged.
Please close this pr and regarding a new issue, you can take up any issue labeled with Up for Grab.
