### ISSUE TITLE
Diabetes Prediction Model

### ISSUE THREAD

**Issue by Dhanush2612** [kritikaparmar-programmer/HealthCheck#97]
ML model to predict diabetes.

**Comment by utkarsh0702** [comment]
@Dhanush2612 It's already built. Please check: https://github.com/kritikaparmar-programmer/HealthCheck/tree/main/Models

**Comment by Dhanush2612** [comment]
@kritikaparmar-programmer can you kindly suggest me amy other model that can be implemented in this project?
